server:
  port: 8061
  servlet:
    context-path: /uid-generator

spring:
  application:
    name: uid-generator
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/snowflakecus?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  instance:
    preferIpAddress: true
    hostname: 127.0.0.1
    instanceId: ${spring.cloud.client.ipAddress:127.0.0.1}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.server.ip:127.0.0.1}:${eureka.server.port:8010}/eureka/

mybatis:
  mapper-locations: classpath*:mapper/*.xml


uid:
  generate:
    timestampBits: 41
    workIdBits: 5
    sequenceBits: 17
    epochStr: 2018-12-21

  workNode:
    nodeId:

logging:
  level:
    com:
      sse:
        mapper: INFO
