server:
  port: 8061

spring:
  application:
    name: uid-generator
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/snowflake
      username: root
      password: root123
      minimum-idle: 3
      connection-timeout: 30000
      maximum-pool-size: 50
      idle-timeout: 60000
      driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath*:mapper/*.xml

uid:
  generate:
    timestampBits: 41
    workerIdBits: 5
    sequenceBits: 17

  server-node:
    node-id: 0



